test:
  callback_url: http://test.host
development:
  callback_url: http://localhost:4200
docker:
  callback_url: http://localhost:3000/dgfip
production:
  callback_url: https://signup.api.gouv.fr/dgfip
