test:
  callback_url: http://test.host
development:
  callback_url: http://localhost:4200
docker:
  callback_url: http://localhost:4200/#/oauth-callback
production:
  callback_url: http://84.39.49.146/#/oauth-callback
