test:
  callback_url: http://test.host
development:
  callback_url: http://localhost:4200
docker:
  callback_url: http://localhost:3000/contractualisation-fc
production:
  callback_url: https://next.particulier.api.gouv.fr/contractualisation-fc
